### ISSUE TITLE
panic: nil context

### ISSUE THREAD

**Issue by mooop12** [lazyhacker/youtube-copy#1]
Hi, I can't get this program to run. When I start it, after putting in the auth code I get this error:

```
panic: nil context

goroutine 1 [running]:
net/http.(*Request).WithContext(0xc04211c300, 0x0, 0x0, 0xc042135170)
        C:/Go/src/net/http/request.go:327 +0x1c9
golang.org/x/net/context/ctxhttp.Do(0x0, 0x0, 0x89ad80, 0xc04211c300, 0x21, 0xc0420c6b40, 0xc04211c300)
        C:/Users/bartek/go/src/golang.org/x/net/context/ctxhttp/ctxhttp.go:30 +0x5d
golang.org/x/oauth2/internal.RetrieveToken(0x0, 0x0, 0xc04201a140, 0x48, 0xc04200e820, 0x18, 0xc04200a7b0, 0x2a, 0xc042135140, 0x0, ...)
        C:/Users/bartek/go/src/golang.org/x/oauth2/internal/token.go:193 +0x219
golang.org/x/oauth2.retrieveToken(0x0, 0x0, 0xc0420e27e0, 0xc042135140, 0xc042098fd8, 0xc0420676b8, 0x4c11de)
        C:/Users/bartek/go/src/golang.org/x/oauth2/token.go:153 +0x90
golang.org/x/oauth2.(*Config).Exchange(0xc0420e27e0, 0x0, 0x0, 0xc042133c20, 0x2d, 0x0, 0xc042114000, 0x102)
        C:/Users/bartek/go/src/golang.org/x/oauth2/oauth2.go:179 +0x243
lazyhackergo.com/youtube-copy/auth.buildOAuthHTTPClient(0x71e9af, 0x31, 0x747fe0, 0x6c97a0, 0xc04203cb10)
        C:/Users/bartek/go/src/lazyhackergo.com/youtube-copy/auth/auth.go:186 +0x5c1
lazyhackergo.com/youtube-copy/auth.Authenticate(0x8676e0, 0xc042070a50, 0x69dd80, 0x748000, 0x6c97a0)
        C:/Users/bartek/go/src/lazyhackergo.com/youtube-copy/auth/auth.go:203 +0xaa
main.main()
        C:/Users/bartek/go/src/lazyhackergo.com/youtube-copy/youtube-copy.go:121 +0xe9
```

Any idea what might be wrong?

**Comment by lazyhacker** [comment]
How are you running the command?

**Comment by mooop12** [comment]
I go to the go/bin directory and just start the executable. The issue is the same on my Linux machine by the way.

**Comment by mooop12** [comment]
I managed to fix it by replacing references to `ctx` in [this](https://github.com/lazyhacker/youtube-copy/blob/master/auth/auth.go#L132)  method to `oauth2.NoContext`, as in the OAuth2 examples. It seems to be working but as I've never used go before I'm not entirely sure if it is correct.

I'm already importing my subscription but there seems to be a limit separate from the general quota. Do you have any idea when it resets? I managed to import 75 subscriptions before they blocked me.
